### ISSUE TITLE
Stdout error

### ISSUE THREAD

**Issue by surajdevesan** [palashmaran/libsandbox#1]
I am trying to run the code using nodejs execute frunction but i am getting a error as
exec error: Error: Command failed: Traceback (most recent call last):
  File "../../libsandbox/Sandbox/sample2.py", line 131, in <module>
    sys.exit(main(sys.argv))
  File "../../libsandbox/Sandbox/sample2.py", line 68, in main
    msb = MiniSandbox(**cookbook)
AssertionError: stdout should be writable by current user

when i am running in the terminal the code is working but cant exceute it from nodejs.

**Comment by palashmaran** [comment]
Set var/www owner to apache

**Comment by surajdevesan** [comment]
Got the problem it was not adding 2>&1 in the script running the sandbox redirectting the error and stdout to output file

**Comment by palashmaran** [comment]
Chmod u+x sample2.py
